eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/504880813/spring_cloud_config_test.git
          search-paths: hello_word_config
  application:
    name: config-server
management:
   security:
    enabled: false